<a href="https://colab.research.google.com/github/0Park/Deeplearning-NLP/blob/master/make_text_using_RNN_ipynbx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [ ]:
text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

t=Tokenizer()
t.fit_on_texts([text])
vocab_size=len(t.word_index)+1
print('단어 집합의 크기: %d'% vocab_size)

단어 집합의 크기: 12


In [ ]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [ ]:
sequences=list()
for line in text.split('\n'):
  encoded=t.texts_to_sequences([line])[0]
  for i in range(1,len(encoded)):
    sequence=encoded[:i+1]
    sequences.append(sequence)
print('학습에 사용할 샘플의 개수:%d' %len(sequences))

학습에 사용할 샘플의 개수:11


In [ ]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [ ]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이:{}'.format(max_len))

샘플의 최대 길이:6


In [ ]:
sequences=pad_sequences(sequences,maxlen=max_len,padding='pre')

In [ ]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [ ]:
sequences=np.array(sequences)
X=sequences[:,:-1]
y=sequences[:,-1]

In [ ]:
print(X)
print(y)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]
[ 3  1  4  5  1  7  1  9 10  1 11]


In [ ]:
# one hot encoding
y=to_categorical(y,num_classes=vocab_size)
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
# construct model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Dense,SimpleRNN

model=Sequential()
model.add(Embedding(vocab_size,10,input_length=max_len-1)) # cause i seperate the label from data, the length of x is 5
model.add(SimpleRNN(32))
model.add(Dense(vocab_size,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=200,verbose=2)

Epoch 1/200
1/1 - 0s - loss: 2.4808 - accuracy: 0.0000e+00
Epoch 2/200
1/1 - 0s - loss: 2.4688 - accuracy: 0.0909
Epoch 3/200
1/1 - 0s - loss: 2.4567 - accuracy: 0.1818
Epoch 4/200
1/1 - 0s - loss: 2.4443 - accuracy: 0.2727
Epoch 5/200
1/1 - 0s - loss: 2.4316 - accuracy: 0.2727
Epoch 6/200
1/1 - 0s - loss: 2.4184 - accuracy: 0.2727
Epoch 7/200
1/1 - 0s - loss: 2.4047 - accuracy: 0.2727
Epoch 8/200
1/1 - 0s - loss: 2.3903 - accuracy: 0.2727
Epoch 9/200
1/1 - 0s - loss: 2.3751 - accuracy: 0.2727
Epoch 10/200
1/1 - 0s - loss: 2.3593 - accuracy: 0.3636
Epoch 11/200
1/1 - 0s - loss: 2.3425 - accuracy: 0.3636
Epoch 12/200
1/1 - 0s - loss: 2.3249 - accuracy: 0.3636
Epoch 13/200
1/1 - 0s - loss: 2.3065 - accuracy: 0.3636
Epoch 14/200
1/1 - 0s - loss: 2.2871 - accuracy: 0.3636
Epoch 15/200
1/1 - 0s - loss: 2.2668 - accuracy: 0.3636
Epoch 16/200
1/1 - 0s - loss: 2.2457 - accuracy: 0.3636
Epoch 17/200
1/1 - 0s - loss: 2.2238 - accuracy: 0.3636
Epoch 18/200
1/1 - 0s - loss: 2.2012 - accuracy: 0.36

In [ ]:
def sentence_genration(model,t,current_word,n):
  init_word=current_word
  sentence=''
  for _ in range(n):
    encoded=t.texts_to_sequences([current_word])[0]
    encoded=pad_sequences([encoded],maxlen=5,padding='pre')
    result=model.predict_classes(encoded,verbose=0)

    for word,index in t.word_index.items():
      if index == result:
        break
    current_word=current_word+ ' ' + word
    sentence=sentence + ' ' + word
  sentence=init_word + sentence

  return sentence
  


In [ ]:
print(sentence_genration(model,t,'경마장에',4))

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
경마장에 있는 말이 뛰고 있다


In [ ]:
print(sentence_genration(model,t,'그의',2))

그의 말이 법이다


In [ ]:
print(sentence_genration(model,t,'가는',5))

가는 말이 고와야 오는 말이 곱다


Use LSTM

In [ ]:
import pandas as pd
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical


In [ ]:
df=pd.read_csv('/content/datasets_19447_31436_ArticlesApril2018.csv')
df.head()

articleID  ...                                             webURL
0  5adf6684068401528a2aa69b  ...  https://www.nytimes.com/2018/04/24/sports/foot...
1  5adf653f068401528a2aa697  ...  https://www.nytimes.com/2018/04/24/climate/epa...
2  5adf4626068401528a2aa628  ...  https://www.nytimes.com/2018/04/24/dining/noma...
3  5adf40d2068401528a2aa619  ...  https://www.nytimes.com/2018/04/24/world/europ...
4  5adf3d64068401528a2aa60f  ...  https://www.nytimes.com/2018/04/24/world/canad...

[5 rows x 15 columns]

In [ ]:
print('열의 개수:',len(df.columns))
print(df.columns)

열의 개수: 15
Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [ ]:
df['headline'].isnull().values.any()

False

In [ ]:
headline=[]
headline.extend(list(df.headline.values))
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [ ]:
print('총 샘플의 개수: {}'.format(len(headline)))

총 샘플의 개수: 1324


In [ ]:
headline=[n for n in headline if n!= "Unknown"]
print('노이즈값 제거 후 샘플의 개수: {}'.format(len(headline)))

노이즈값 제거 후 샘플의 개수: 1214


In [ ]:
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?']

In [ ]:
def repreprocessing(s):
  s=s.encode("utf8").decode("ascii",'ignore')
  return ''.join(c for c in s if c not in punctuation).lower()
text=[repreprocessing(x) for x in headline]
text[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [ ]:
t=Tokenizer()
t.fit_on_texts(text)
vocab_size=len(t.word_index)+1
print('단어 집합의 크기:%d'%vocab_size)

단어 집합의 크기:3494


In [ ]:
sequences=list()

for line in text:
  encoded=t.texts_to_sequences([line])[0]
  for i in range(1,len(encoded)):
    sequence=encoded[:i+1]
    sequences.append(sequence)
sequences[:11]

[[99, 269],
 [99, 269, 371],
 [99, 269, 371, 1115],
 [99, 269, 371, 1115, 582],
 [99, 269, 371, 1115, 582, 52],
 [99, 269, 371, 1115, 582, 52, 7],
 [99, 269, 371, 1115, 582, 52, 7, 2],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116],
 [100, 3]]

In [ ]:
index_to_word={}
for key, value in t.word_index.items():
  index_to_word[value]=key
print('빈도수 상위 582번 단어:{}'.format(index_to_word[2]))

빈도수 상위 582번 단어:a


In [ ]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))


샘플의 최대 길이 : 24


In [ ]:
sequences=pad_sequences(sequences,maxlen=max_len,padding='pre')
print(sequences[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]


In [ ]:
sequences=np.array(sequences)
X=sequences[:,:-1]
y=sequences[:,-1]
print(X[:3])
print(y[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0  99]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0  99 269]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0  99 269 371]]
[ 269  371 1115]


In [ ]:
y=to_categorical(y,num_classes=vocab_size)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Dense,LSTM

model=Sequential()
model.add(Embedding(vocab_size,10,input_length=max_len-1))
model.add(LSTM(128))
model.add(Dense(vocab_size,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=200,verbose=2)


Epoch 1/200
244/244 - 6s - loss: 7.6586 - accuracy: 0.0287
Epoch 2/200
244/244 - 6s - loss: 7.1147 - accuracy: 0.0283
Epoch 3/200
244/244 - 6s - loss: 6.9754 - accuracy: 0.0326
Epoch 4/200
244/244 - 6s - loss: 6.8510 - accuracy: 0.0392
Epoch 5/200
244/244 - 6s - loss: 6.7089 - accuracy: 0.0433
Epoch 6/200
244/244 - 6s - loss: 6.5429 - accuracy: 0.0477
Epoch 7/200
244/244 - 6s - loss: 6.3619 - accuracy: 0.0520
Epoch 8/200
244/244 - 6s - loss: 6.1682 - accuracy: 0.0593
Epoch 9/200
244/244 - 6s - loss: 5.9712 - accuracy: 0.0600
Epoch 10/200
244/244 - 6s - loss: 5.7806 - accuracy: 0.0666
Epoch 11/200
244/244 - 6s - loss: 5.5991 - accuracy: 0.0711
Epoch 12/200
244/244 - 6s - loss: 5.4324 - accuracy: 0.0752
Epoch 13/200
244/244 - 6s - loss: 5.2723 - accuracy: 0.0824
Epoch 14/200
244/244 - 6s - loss: 5.1209 - accuracy: 0.0868
Epoch 15/200
244/244 - 6s - loss: 4.9766 - accuracy: 0.0938
Epoch 16/200
244/244 - 6s - loss: 4.8387 - accuracy: 0.1077
Epoch 17/200
244/244 - 6s - loss: 4.7066 - accura

In [ ]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=23, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [ ]:
print(sentence_generation(model,t,'how',10))

how can a doctor grapple with the epidemic of cost coverage
